version: '3.8'
services:
  mongo:
    restart: always
    container_name: mongo
    image: 'mongo:4.1.3'
    ports:
      - "27017:27017"
    networks:
      - recipe-app
    volumes:
      - ./db:/data/db

  server:
    restart: always
    container_name: server
    build: ./server
    image: group10ict/server:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - recipe-app
  
  client:
    restart: always
    container_name: client
    build: ./client
    image: group10ict/client:latest
    ports:
      - "3000:3000"
    networks:
      - recipe-app

  nginx:
    restart: always
    container_name: nginx
    build: ./nginx
    image: group10ict/nginx:latest
    ports: 
      - "8080:80"
    networks:
      - recipe-app

networks:
  recipe-app:
    driver: bridge