version: '3.8'
services:
  mongo:
    restart: always
    container_name: mongo
    image: 'mongo:4.1.3'
    ports:
      - "27017:27017"
    networks:
      - recipe-app
    volumes:
      - ./db:/data/db

  server:
    restart: always
    container_name: server
    build: ./server
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGODB_URL: 'mongodb://mongo:27017/recipe'
      SENDGRID_API_KEY: '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'
      JWT_SECRET: 'oneloveonefuture'
    depends_on:
      - mongo
    networks:
      - recipe-app
  
  client:
    restart: always
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - recipe-app

  nginx:
    restart: always
    container_name: nginx
    build: ./nginx
    ports: 
      - "8080:80"
    networks:
      - recipe-app

networks:
  recipe-app:
    driver: bridge