export const avatarData = [
    {
      id: 1,
      name: "Nguyen Van A",
      username: "a1",
      email: "a1@gmail.com",
      password: "123",
      numOfFavourite: 3,
      favourited_recipes: [1,2,3],
      avatar: "https://static.chotot.com/storage/chotot-kinhnghiem/c2c/2019/02/cho-nhat.jpg",
      time: "28-11-2021",
      own_recipes: [1,2,3],
    },
    { id: 2,
      name: "Nguyen Van B",
      username: "a1",
      email: "a1@gmail.com",
      password: "123",
      numOfFavourite: 3,
      favourited_recipes: [1,2,3],
      avatar: "https://static.chotot.com/storage/chotot-kinhnghiem/c2c/2019/02/cho-nhat.jpg",
      time: "28-11-2021",
      own_recipes: [1,2,3],
    },
    { id:103,
      name: "Nguyen Van C",
      username: "a1",
      email: "a1@gmail.com",
      password: "123",
      numOfFavourite: 3,
      favourited_recipes: [1,2,3],
      avatar: "https://static.chotot.com/storage/chotot-kinhnghiem/c2c/2019/02/cho-nhat.jpg",
      time: "28-11-2021",
      own_recipes: [1,2,3],
    },
    { id:4,
      name: "Nguyen Van D",
      username: "a1",
      email: "a1@gmail.com",
      password: "123",
      numOfFavourite: 3,
      favourited_recipes: [1,2,3],
      avatar: "https://static.chotot.com/storage/chotot-kinhnghiem/c2c/2019/02/cho-nhat.jpg",
      time: "28-11-2021",
      own_recipes: [1,2,3],
    },
  ];